### ISSUE TITLE
Can't see how to use declaration style

### ISSUE THREAD

**Issue by owencm** [lukaskollmer/objc#2]
Hi, thanks for your work on this project!

I'm trying to work with CoreGraphics and can't see how to do that with `objc`

For example, I'm trying to call `CGEventCreate(null)` by writing:

```
const objc = require('objc')
objc.import('Cocoa')
objc.import('Framework')
const {CGEventCreate} = objc
const test = CGEventCreate(null)
```

but I'm getting back an error that `CGEventCreate` is not a function, and that it's value is `'H��AW'`.

Any pointers for how to get this to work?

**Comment by lukaskollmer** [comment]
The problem is that `CoreGraphics` is entirely written in C, meaning that you'll have to access it via the `ffi` module:

```js
const ffi = require('ffi');
const objc = require('objc');
objc.import('CoreGraphics');

const lib = new ffi.Library(null, {
  CGEventCreate: ['pointer', ['pointer']]
});

const event = lib.CGEventCreate(null);
```
