### ISSUE TITLE
Delegates?

### ISSUE THREAD

**Issue by jmbldwn** [lukaskollmer/objc#3]
Bravo for doing this.  I'm jonesing to pass in a delegate that ends up as a callback/event in JS.  I see you support blocks; is there a way to define a delegate?

**Comment by lukaskollmer** [comment]
the only way to use objc-style delegates is by creating a custom class which implements the methods declared in the delegate's protocol.

see [this](https://github.com/lukaskollmer/objc/blob/master/examples/delegate.js) for an example implementation for `NSFileManagerDelegate` and [this](https://github.com/lukaskollmer/objc/blob/master/examples/classes.js) for a general example on how to create a custom class

**Comment by jmbldwn** [comment]
Cool.  Will try this out.
