### ISSUE TITLE
Unhelpful error message when framework not found

### ISSUE THREAD

**Issue by hhas** [lukaskollmer/objc#34]
The `importFramework` utility function throws an unhelpful error message when `NSBundle.bundleWithPath_(path)` returns `null` (e.g. because the path was invalid):

    /Users/foo/node_modules/objc/src/util.js:25
      bundle.load();
    TypeError: Cannot read properties of null (reading 'load')

I suggest inserting a null check before the `bundle.load()` line that throws a descriptive error:

      if (bundle === null) { throw Error(`Framework not found: '${path}'`); }

**Comment by lukaskollmer** [comment]
Yeah this seems like a good idea, I'll add that. Thanks for the feedback.

**Comment by lukaskollmer** [comment]
Done, fixed in [0.23.0](https://github.com/lukaskollmer/objc/releases/tag/v0.23.0)
