### ISSUE TITLE
Clarification of Object->NSDictionary Conversion

### ISSUE THREAD

**Issue by jmbldwn** [lukaskollmer/objc#7]
I have a property I need to set with a dictionary. The obj.ns() method says it turns objects into dictionaries, but NSDictionary keys can be more than just strings.  For example to configure video output settings, in Objective C I do this:
```
videoDataOutput.videoSettings = @{
    (id)kCVPixelBufferPixelFormatTypeKey: [NSNumber numberWithUnsignedInteger:kCVPixelFormatType_32BGRA]
};
```    
I can't quite figure out how to construct the JS object to pass to obj.ns() to make this happen.  Am I missing something?

**Comment by lukaskollmer** [comment]
According to the [ECMA spec](http://www.ecma-international.org/ecma-262/6.0/#sec-object-type),
> Properties are identified using key values. A property key value is either an ECMAScript String value or a Symbol value

`objc.ns` therefore will always create a `NSDictionary` w/ `NSString` keys. If you want some custom `id` as a key, you'll have to create a [`NSMutableDictionary`](https://developer.apple.com/documentation/foundation/nsmutabledictionary?language=objc) and fill it via [`setObject:forKey:`](https://developer.apple.com/documentation/foundation/nsmutabledictionary/1411616-setobject?language=objc)

**Comment by jmbldwn** [comment]
Thanks. This works.  It might be nice someday to have a smoother way to pull in .h files that define constants that the runtime expects, including conversion from 4BCC codes to numbers.  It ends up being a little clunky to have to do this manually.
